//! `grove hooks install|uninstall|status` — manage Claude Code hooks.
//!
//! Manages orchestrator hooks in `.claude/settings.local.json`.
//! The canonical hook configuration lives in `.overstory/hooks.json`
//! (generated by `grove init`). Running `grove hooks install` copies hooks
//! from there into `.claude/settings.local.json` where Claude Code discovers them.
//!
//! This keeps hooks config in `.overstory/` while placing a minimal copy in
//! `.claude/` only when the user explicitly opts in.

use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

use crate::config::resolve_project_root;
use crate::json::json_output;
use crate::logging::{print_hint, print_success, print_warning};

// ---------------------------------------------------------------------------
// Hook merge logic (pub for testing)
// ---------------------------------------------------------------------------

/// Check if two hook entries are identical (same matcher + same command list).
fn is_duplicate_entry(a: &Value, b: &Value) -> bool {
    let a_matcher = a.get("matcher").and_then(Value::as_str).unwrap_or("");
    let b_matcher = b.get("matcher").and_then(Value::as_str).unwrap_or("");
    if a_matcher != b_matcher {
        return false;
    }
    let a_hooks = a.get("hooks").and_then(Value::as_array);
    let b_hooks = b.get("hooks").and_then(Value::as_array);
    match (a_hooks, b_hooks) {
        (Some(ah), Some(bh)) => {
            if ah.len() != bh.len() {
                return false;
            }
            ah.iter().zip(bh.iter()).all(|(ac, bc)| {
                ac.get("type").and_then(Value::as_str) == bc.get("type").and_then(Value::as_str)
                    && ac.get("command").and_then(Value::as_str)
                        == bc.get("command").and_then(Value::as_str)
            })
        }
        (None, None) => true,
        _ => false,
    }
}

/// Merge two hook maps by event type, deduplicating identical entries.
///
/// Preserves all existing entries and appends only non-duplicate incoming
/// entries per event type.
pub fn merge_hooks_by_event_type(
    existing: &serde_json::Map<String, Value>,
    incoming: &serde_json::Map<String, Value>,
) -> serde_json::Map<String, Value> {
    let mut merged = existing.clone();

    for (event_type, incoming_entries) in incoming {
        let incoming_arr = match incoming_entries.as_array() {
            Some(a) => a,
            None => continue,
        };

        if !merged.contains_key(event_type) {
            merged.insert(event_type.clone(), incoming_entries.clone());
            continue;
        }

        let existing_entries = merged
            .get(event_type)
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();

        let mut combined = existing_entries.clone();
        for entry in incoming_arr {
            let is_dupe = existing_entries
                .iter()
                .any(|e| is_duplicate_entry(e, entry));
            if !is_dupe {
                combined.push(entry.clone());
            }
        }
        merged.insert(event_type.clone(), Value::Array(combined));
    }

    merged
}

// ---------------------------------------------------------------------------
// Pre-commit hook
// ---------------------------------------------------------------------------

const PRECOMMIT_MARKER: &str = "grove-conflict-marker-check";

const PRECOMMIT_SCRIPT: &str = r#"#!/bin/sh
# grove-conflict-marker-check

# 1. Auto-format staged Rust files
if command -v rustfmt >/dev/null 2>&1; then
    STAGED_RS=$(git diff --cached --name-only --diff-filter=ACM -- '*.rs')
    if [ -n "$STAGED_RS" ]; then
        echo "$STAGED_RS" | xargs rustfmt
        echo "$STAGED_RS" | xargs git add
    fi
fi

# 2. Conflict marker check (staged files only)
CONFLICT_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.rs' | xargs grep -l '<<<<<<< ' 2>/dev/null)
if [ -n "$CONFLICT_FILES" ]; then
    echo 'ERROR: Conflict markers found in staged .rs files:'
    echo "$CONFLICT_FILES"
    echo ''
    echo 'Resolve conflicts before committing.'
    echo 'If these are intentional string literals in test data, use: git commit --no-verify'
    exit 1
fi

exit 0
"#;

/// Install a git pre-commit hook that rejects conflict markers in .rs files.
///
/// Uses `git rev-parse --git-common-dir` to locate the hooks directory.
/// Skips if an existing hook not written by grove is present (unless force).
pub fn install_git_precommit_hook(project_root: &Path, force: bool) -> Result<(), String> {
    let output = std::process::Command::new("git")
        .args(["rev-parse", "--git-common-dir"])
        .current_dir(project_root)
        .output()
        .map_err(|e| format!("Failed to run git: {e}"))?;

    if !output.status.success() {
        return Err("Not a git repository".to_string());
    }

    let git_dir_raw = String::from_utf8_lossy(&output.stdout).trim().to_string();
    let git_dir = if Path::new(&git_dir_raw).is_absolute() {
        PathBuf::from(&git_dir_raw)
    } else {
        project_root.join(&git_dir_raw)
    };
    let hooks_dir = git_dir.join("hooks");

    fs::create_dir_all(&hooks_dir).map_err(|e| format!("Failed to create hooks directory: {e}"))?;

    let hook_path = hooks_dir.join("pre-commit");

    // Skip if existing hook wasn't written by grove, unless force
    if hook_path.exists() && !force {
        let existing = fs::read_to_string(&hook_path)
            .map_err(|e| format!("Failed to read existing pre-commit hook: {e}"))?;
        if !existing.contains(PRECOMMIT_MARKER) {
            return Ok(());
        }
    }

    fs::write(&hook_path, PRECOMMIT_SCRIPT)
        .map_err(|e| format!("Failed to write pre-commit hook: {e}"))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&hook_path, fs::Permissions::from_mode(0o755))
            .map_err(|e| format!("Failed to set hook permissions: {e}"))?;
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Install
// ---------------------------------------------------------------------------

/// Install orchestrator hooks from `.overstory/hooks.json` to
/// `.claude/settings.local.json`.
pub fn execute_install(
    force: bool,
    json: bool,
    project_override: Option<&Path>,
) -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| e.to_string())?;
    let project_root = resolve_project_root(&cwd, project_override).map_err(|e| e.to_string())?;

    // Read source hooks from .overstory/hooks.json
    let source_path = project_root.join(".overstory").join("hooks.json");
    if !source_path.exists() {
        return Err("No hooks.json found in .overstory/. Run 'grove init' first.".to_string());
    }
    let source_content =
        fs::read_to_string(&source_path).map_err(|e| format!("Failed to read hooks.json: {e}"))?;
    let source_parsed: Value = serde_json::from_str(&source_content)
        .map_err(|e| format!("Failed to parse hooks.json: {e}"))?;
    let incoming_hooks = match source_parsed.get("hooks").and_then(Value::as_object) {
        Some(h) => h.clone(),
        None => return Err("hooks.json missing 'hooks' key".to_string()),
    };

    // Read existing .claude/settings.local.json
    let target_dir = project_root.join(".claude");
    let target_path = target_dir.join("settings.local.json");

    let mut target_config: serde_json::Map<String, Value> = serde_json::Map::new();
    if target_path.exists() {
        let existing_content = fs::read_to_string(&target_path)
            .map_err(|e| format!("Failed to read settings.local.json: {e}"))?;
        let existing: Value = serde_json::from_str(&existing_content)
            .map_err(|e| format!("Failed to parse settings.local.json: {e}"))?;

        if let Value::Object(obj) = existing {
            if obj.contains_key("hooks") && !force {
                println!(
                    "Hooks already present in .claude/settings.local.json\n\
                     Use --force to overwrite."
                );
                return Ok(());
            }
            target_config = obj;
        }
    }

    // Merge hooks
    let existing_hooks = target_config
        .get("hooks")
        .and_then(Value::as_object)
        .cloned();
    let merged_hooks = if let Some(existing) = existing_hooks {
        merge_hooks_by_event_type(&existing, &incoming_hooks)
    } else {
        incoming_hooks
    };
    target_config.insert("hooks".to_string(), Value::Object(merged_hooks));

    // Write
    fs::create_dir_all(&target_dir)
        .map_err(|e| format!("Failed to create .claude directory: {e}"))?;
    let output_json = serde_json::to_string_pretty(&Value::Object(target_config))
        .map_err(|e| format!("Failed to serialize settings: {e}"))?;
    fs::write(&target_path, format!("{output_json}\n"))
        .map_err(|e| format!("Failed to write settings.local.json: {e}"))?;

    // Install pre-commit conflict marker hook
    match install_git_precommit_hook(&project_root, force) {
        Ok(()) => {}
        Err(e) => {
            // Non-fatal: warn but don't fail the install
            print_warning("Could not install pre-commit hook", Some(&e));
        }
    }

    if json {
        #[derive(serde::Serialize)]
        struct Out {
            installed: bool,
            path: String,
        }
        println!(
            "{}",
            json_output(
                "hooks-install",
                &Out {
                    installed: true,
                    path: target_path.to_string_lossy().into_owned()
                }
            )
        );
    } else {
        print_success("Installed orchestrator hooks", None);
        print_hint("Source: .overstory/hooks.json");
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Uninstall
// ---------------------------------------------------------------------------

/// Remove orchestrator hooks from `.claude/settings.local.json`.
pub fn execute_uninstall(json: bool, project_override: Option<&Path>) -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| e.to_string())?;
    let project_root = resolve_project_root(&cwd, project_override).map_err(|e| e.to_string())?;
    let target_path = project_root.join(".claude").join("settings.local.json");

    if !target_path.exists() {
        print_warning(
            "No .claude/settings.local.json found",
            Some("nothing to uninstall"),
        );
        return Ok(());
    }

    let content = fs::read_to_string(&target_path)
        .map_err(|e| format!("Failed to read settings.local.json: {e}"))?;
    let parsed: Value =
        serde_json::from_str(&content).map_err(|e| format!("Failed to parse JSON: {e}"))?;
    let mut obj = match parsed {
        Value::Object(o) => o,
        _ => return Err("settings.local.json is not a JSON object".to_string()),
    };

    if !obj.contains_key("hooks") {
        println!("No hooks found in .claude/settings.local.json \u{2014} nothing to uninstall.");
        return Ok(());
    }

    obj.remove("hooks");

    if obj.is_empty() {
        fs::remove_file(&target_path)
            .map_err(|e| format!("Failed to remove settings.local.json: {e}"))?;
    } else {
        let output_json = serde_json::to_string_pretty(&Value::Object(obj))
            .map_err(|e| format!("Failed to serialize: {e}"))?;
        fs::write(&target_path, format!("{output_json}\n"))
            .map_err(|e| format!("Failed to write settings.local.json: {e}"))?;
    }

    if json {
        #[derive(serde::Serialize)]
        struct Out {
            uninstalled: bool,
        }
        println!(
            "{}",
            json_output("hooks-uninstall", &Out { uninstalled: true })
        );
    } else {
        print_success("Removed hooks from settings.local.json", None);
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Status
// ---------------------------------------------------------------------------

/// Show hooks installation status.
pub fn execute_status(json: bool, project_override: Option<&Path>) -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| e.to_string())?;
    let project_root = resolve_project_root(&cwd, project_override).map_err(|e| e.to_string())?;

    let source_path = project_root.join(".overstory").join("hooks.json");
    let target_path = project_root.join(".claude").join("settings.local.json");

    let source_exists = source_path.exists();
    let installed = if target_path.exists() {
        fs::read_to_string(&target_path)
            .ok()
            .and_then(|c| serde_json::from_str::<Value>(&c).ok())
            .and_then(|v| v.get("hooks").cloned())
            .is_some()
    } else {
        false
    };

    if json {
        #[derive(serde::Serialize)]
        #[serde(rename_all = "camelCase")]
        struct Out {
            source_exists: bool,
            installed: bool,
        }
        println!(
            "{}",
            json_output(
                "hooks-status",
                &Out {
                    source_exists,
                    installed
                }
            )
        );
    } else {
        println!(
            "Hooks source (.overstory/hooks.json): {}",
            if source_exists { "present" } else { "missing" }
        );
        println!(
            "Hooks installed (.claude/settings.local.json): {}",
            if installed { "yes" } else { "no" }
        );
        if !installed && source_exists {
            print_hint("Run grove hooks install to install");
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn write_file(dir: &Path, rel: &str, content: &str) {
        let path = dir.join(rel);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, content).unwrap();
    }

    fn minimal_hooks_json() -> &'static str {
        r#"{"hooks":{"SessionStart":[{"matcher":"","hooks":[{"type":"command","command":"ov prime"}]}]}}"#
    }

    #[test]
    fn test_merge_hooks_by_event_type_new_key() {
        let existing: serde_json::Map<String, Value> = serde_json::Map::new();
        let mut incoming: serde_json::Map<String, Value> = serde_json::Map::new();
        incoming.insert(
            "SessionStart".to_string(),
            serde_json::json!([{"matcher":"","hooks":[]}]),
        );
        let merged = merge_hooks_by_event_type(&existing, &incoming);
        assert!(merged.contains_key("SessionStart"));
    }

    #[test]
    fn test_merge_hooks_by_event_type_no_duplicates() {
        let entry =
            serde_json::json!([{"matcher":"","hooks":[{"type":"command","command":"foo"}]}]);
        let mut existing: serde_json::Map<String, Value> = serde_json::Map::new();
        existing.insert("SessionStart".to_string(), entry.clone());
        let mut incoming: serde_json::Map<String, Value> = serde_json::Map::new();
        incoming.insert("SessionStart".to_string(), entry);

        let merged = merge_hooks_by_event_type(&existing, &incoming);
        // Should only have 1 entry (deduped)
        let entries = merged["SessionStart"].as_array().unwrap();
        assert_eq!(entries.len(), 1);
    }

    #[test]
    fn test_merge_hooks_by_event_type_appends_new() {
        let entry_a =
            serde_json::json!([{"matcher":"","hooks":[{"type":"command","command":"cmd-a"}]}]);
        let entry_b =
            serde_json::json!([{"matcher":"","hooks":[{"type":"command","command":"cmd-b"}]}]);
        let mut existing: serde_json::Map<String, Value> = serde_json::Map::new();
        existing.insert("SessionStart".to_string(), entry_a);
        let mut incoming: serde_json::Map<String, Value> = serde_json::Map::new();
        incoming.insert("SessionStart".to_string(), entry_b);

        let merged = merge_hooks_by_event_type(&existing, &incoming);
        let entries = merged["SessionStart"].as_array().unwrap();
        assert_eq!(entries.len(), 2);
    }

    #[test]
    fn test_install_hooks_no_source_file() {
        let result = execute_install(false, false, Some(Path::new("/tmp")));
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("No hooks.json"));
    }

    #[test]
    fn test_install_hooks_creates_settings_file() {
        let dir = TempDir::new().unwrap();
        write_file(dir.path(), ".overstory/hooks.json", minimal_hooks_json());

        let result = execute_install(false, false, Some(dir.path()));
        assert!(result.is_ok(), "install failed: {result:?}");

        let settings_path = dir.path().join(".claude/settings.local.json");
        assert!(settings_path.exists());
        let content = fs::read_to_string(&settings_path).unwrap();
        let parsed: Value = serde_json::from_str(&content).unwrap();
        assert!(parsed.get("hooks").is_some());
    }

    #[test]
    fn test_install_hooks_preserves_existing_keys() {
        let dir = TempDir::new().unwrap();
        write_file(dir.path(), ".overstory/hooks.json", minimal_hooks_json());
        write_file(
            dir.path(),
            ".claude/settings.local.json",
            r#"{"env":{"FOO":"bar"}}"#,
        );

        execute_install(false, false, Some(dir.path())).unwrap();

        let content = fs::read_to_string(dir.path().join(".claude/settings.local.json")).unwrap();
        let parsed: Value = serde_json::from_str(&content).unwrap();
        assert_eq!(parsed["env"]["FOO"].as_str(), Some("bar"));
        assert!(parsed.get("hooks").is_some());
    }

    #[test]
    fn test_install_hooks_blocks_without_force_when_exists() {
        let dir = TempDir::new().unwrap();
        write_file(dir.path(), ".overstory/hooks.json", minimal_hooks_json());
        write_file(
            dir.path(),
            ".claude/settings.local.json",
            r#"{"hooks":{"Stop":[]}}"#,
        );

        // Second install without --force should succeed but not overwrite
        let result = execute_install(false, false, Some(dir.path()));
        assert!(result.is_ok());
        // Content should still be the original
        let content = fs::read_to_string(dir.path().join(".claude/settings.local.json")).unwrap();
        assert!(content.contains("\"Stop\""));
        // SessionStart from source should NOT be present (not overwritten)
        assert!(!content.contains("\"SessionStart\""));
    }

    #[test]
    fn test_install_hooks_force_overwrites() {
        let dir = TempDir::new().unwrap();
        write_file(dir.path(), ".overstory/hooks.json", minimal_hooks_json());
        write_file(
            dir.path(),
            ".claude/settings.local.json",
            r#"{"hooks":{"Stop":[]}}"#,
        );

        execute_install(true, false, Some(dir.path())).unwrap();
        let content = fs::read_to_string(dir.path().join(".claude/settings.local.json")).unwrap();
        assert!(content.contains("SessionStart"));
    }

    #[test]
    fn test_uninstall_hooks_removes_hooks_key() {
        let dir = TempDir::new().unwrap();
        write_file(
            dir.path(),
            ".claude/settings.local.json",
            r#"{"env":{"FOO":"bar"},"hooks":{"Stop":[]}}"#,
        );

        execute_uninstall(false, Some(dir.path())).unwrap();

        let content = fs::read_to_string(dir.path().join(".claude/settings.local.json")).unwrap();
        let parsed: Value = serde_json::from_str(&content).unwrap();
        assert!(parsed.get("hooks").is_none());
        assert_eq!(parsed["env"]["FOO"].as_str(), Some("bar"));
    }

    #[test]
    fn test_uninstall_hooks_removes_file_when_empty() {
        let dir = TempDir::new().unwrap();
        write_file(
            dir.path(),
            ".claude/settings.local.json",
            r#"{"hooks":{"Stop":[]}}"#,
        );

        execute_uninstall(false, Some(dir.path())).unwrap();
        assert!(!dir.path().join(".claude/settings.local.json").exists());
    }

    #[test]
    fn test_uninstall_hooks_no_settings_file() {
        let result = execute_uninstall(false, Some(Path::new("/tmp")));
        assert!(result.is_ok());
    }

    #[test]
    fn test_status_hooks_no_files() {
        let result = execute_status(false, Some(Path::new("/tmp")));
        assert!(result.is_ok());
    }

    #[test]
    fn test_status_hooks_json_output() {
        let dir = TempDir::new().unwrap();
        write_file(dir.path(), ".overstory/hooks.json", minimal_hooks_json());
        write_file(
            dir.path(),
            ".claude/settings.local.json",
            r#"{"hooks":{"Stop":[]}}"#,
        );

        let result = execute_status(true, Some(dir.path()));
        assert!(result.is_ok());
    }

    #[test]
    fn test_is_duplicate_entry_same() {
        let a = serde_json::json!({"matcher":"","hooks":[{"type":"command","command":"foo"}]});
        let b = a.clone();
        assert!(is_duplicate_entry(&a, &b));
    }

    #[test]
    fn test_is_duplicate_entry_different_command() {
        let a = serde_json::json!({"matcher":"","hooks":[{"type":"command","command":"foo"}]});
        let b = serde_json::json!({"matcher":"","hooks":[{"type":"command","command":"bar"}]});
        assert!(!is_duplicate_entry(&a, &b));
    }

    #[test]
    fn test_is_duplicate_entry_different_matcher() {
        let a = serde_json::json!({"matcher":"Bash","hooks":[{"type":"command","command":"foo"}]});
        let b = serde_json::json!({"matcher":"","hooks":[{"type":"command","command":"foo"}]});
        assert!(!is_duplicate_entry(&a, &b));
    }

    fn git_init(dir: &Path) {
        std::process::Command::new("git")
            .args(["init"])
            .current_dir(dir)
            .output()
            .expect("git init failed");
    }

    #[test]
    fn test_install_git_precommit_hook_creates_file() {
        let dir = TempDir::new().unwrap();
        git_init(dir.path());

        let result = install_git_precommit_hook(dir.path(), false);
        assert!(result.is_ok(), "hook install failed: {result:?}");

        let hook_path = dir.path().join(".git/hooks/pre-commit");
        assert!(hook_path.exists());
        let content = fs::read_to_string(&hook_path).unwrap();
        assert!(content.contains("grove-conflict-marker-check"));
        assert!(content.contains("<<<<<<< "));

        // Verify it's executable
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = fs::metadata(&hook_path).unwrap().permissions();
            assert!(perms.mode() & 0o111 != 0, "hook should be executable");
        }
    }

    #[test]
    fn test_install_git_precommit_hook_skip_existing() {
        let dir = TempDir::new().unwrap();
        git_init(dir.path());

        let hooks_dir = dir.path().join(".git/hooks");
        fs::create_dir_all(&hooks_dir).unwrap();
        let hook_path = hooks_dir.join("pre-commit");
        // Write a hook NOT from grove
        fs::write(&hook_path, "#!/bin/sh\n# custom hook\nexit 0\n").unwrap();

        let result = install_git_precommit_hook(dir.path(), false);
        assert!(result.is_ok());

        // File should be unchanged (not overwritten)
        let content = fs::read_to_string(&hook_path).unwrap();
        assert!(content.contains("custom hook"));
        assert!(!content.contains("grove-conflict-marker-check"));
    }

    #[test]
    fn test_install_git_precommit_hook_force_overwrites() {
        let dir = TempDir::new().unwrap();
        git_init(dir.path());

        let hooks_dir = dir.path().join(".git/hooks");
        fs::create_dir_all(&hooks_dir).unwrap();
        let hook_path = hooks_dir.join("pre-commit");
        // Write a hook NOT from grove
        fs::write(&hook_path, "#!/bin/sh\n# custom hook\nexit 0\n").unwrap();

        let result = install_git_precommit_hook(dir.path(), true);
        assert!(result.is_ok());

        // File should be overwritten with grove hook
        let content = fs::read_to_string(&hook_path).unwrap();
        assert!(content.contains("grove-conflict-marker-check"));
    }
}
